apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"PrometheusRule","metadata":{"annotations":{},"creationTimestamp":"2019-09-30T22:50:57Z","generation":1,"labels":{"prometheus":"cachet","role":"alert-rules"},"name":"prometheus-cachet-rules","namespace":"cachet","resourceVersion":"1429878","selfLink":"/apis/monitoring.coreos.com/v1/namespaces/cachet/prometheusrules/prometheus-cachet-rules","uid":"c46b82a6-e3d4-11e9-8caf-0addb7b61b1c"},"spec":{"groups":[{"name":"black box","rules":[{"alert":"BlackBoxFailure","expr":"(rate(black_box_test_failures_total[10m]) / (rate(black_box_test_runs_total[10m]) \u003e 0) * 100) \u003e 10","for":"10m"}]}]}}
    labels:
      prometheus: cachet
      role: alert-rules
    name: prometheus-cachet-rules
    namespace: cachet
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/cachet/prometheusrules/prometheus-cachet-rules
  spec:
    groups:
    - name: black box
      rules:
      - alert: BlackBoxFailure
        expr: (rate(black_box_test_failures_total[10m]) / (rate(black_box_test_runs_total[10m])
          > 0) * 100) > 10
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Black Box Tester Fail"
          description: "Black box tester failure, check promethues for details."

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
