apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app":"black-box-runner"},"name":"black-box-runner","namespace":"cachet"},"spec":{"endpoints":[{"interval":"10s","port":"metrics"}],"namespaceSelector":{"matchNames":["black-box-runner"]},"selector":{"matchLabels":{"app":"black-box-runner"}}}}
    labels:
      app: black-box-runner
    name: black-box-runner
    namespace: cachet
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/cachet/servicemonitors/black-box-runner
  spec:
    endpoints:
    - interval: 10s
      port: "8000"
    namespaceSelector:
      matchNames:
      - black-box-runner
    selector:
      matchLabels:
        app: black-box-runner
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
